version: '3.8'

services:
  frontend:
    build: ./frontend
    image: laaouafifatiha/todo-frontend:latest
    container_name: todo_frontend
    ports:
      - "3000:80"
    environment:
      - REACT_APP_API_URL=http://backend:5000
    depends_on:
      - backend
    restart: always
    networks:
      - todo-network

  backend:
    build: ./backend
    image: laaouafifatiha/todo-backend:latest
    container_name: todo_backend
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/tododb
      - FLASK_ENV=development
    depends_on:
      - mongo
    restart: always
    networks:
      - todo-network

  mongo:
    image: mongo:6
    container_name: todo_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
      - ./mongodb/init-db.js:/docker-entrypoint-initdb.d/init-db.js:ro
    restart: always
    networks:
      - todo-network

volumes:
  mongo_data:

networks:
  todo-network:
    driver: bridge


